bug fix in merge CDS
I ran into a `AttributeError: 'ExtendedFeature' object has no attribute 'extended_attributes'` while trying to merge features from Prodigal and MGA. Looking through the code seems like maybe this needs an update to look at the 'annotations' property. 

Please verify it is working as intended.